### ISSUE TITLE
Is c:orderedListGroup component necessary for aura tester?

### ISSUE THREAD

**Issue by bdovh** [rapsacnz/DatePicker#1]
When trying to deploy the following error happens
Error  force-app/main/default/aura/AuraTester/AuraTester.app  No COMPONENT named markup://c:orderedListGroup found

**Comment by rapsacnz** [comment]
No, it's not necessary. I converted another project to make this date picker - I'll fix shortly.

**Comment by rapsacnz** [comment]
Ok, I've removed the dependency on the orderedListGroup
